# 테스트할 분류(classification) 작업에 대한 설정
classification_test:
  # 실행할 명령어
  command: "bin/imagenet_classification -m assets/models/EfficientNetB0_4.dxnn -i example/imagenet_classification/imagenet_val_map.txt -p sample/ILSVRC2012/"
  # stop timeout
  timeout_sec: 3
